In [2]:
import numpy as np

In [3]:
arr = np.array([1,7,9,4])
arr

array([1, 7, 9, 4])

In [4]:
a = [1,3.4,'hi']
np.array(a)

array(['1', '3.4', 'hi'], dtype='<U32')

In [6]:
arr= np.arange(1,11,3)
arr

array([ 1,  4,  7, 10])

In [7]:
ar1 = np.zeros(7)
ar1

array([0., 0., 0., 0., 0., 0., 0.])

In [10]:
ar2= np.ones((5,2))
ar2

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
ar3 = np.linspace(0,4,10)
ar3

array([0.        , 0.44444444, 0.88888889, 1.33333333, 1.77777778,
       2.22222222, 2.66666667, 3.11111111, 3.55555556, 4.        ])

In [13]:
np.random.rand(3)

array([0.1594989 , 0.51525117, 0.03123174])

In [16]:
np.random.randn(4)
# normalized no. and between -3 to 3

array([ 2.07217726,  0.99467305, -0.46526523, -0.26481477])

In [17]:
np.random.randint(7)
# generate a random no. between 0-7

3

In [18]:
np.random.randint(10,20,2)
# generate two no. between 10 and 20 

array([19, 16], dtype=int32)

In [20]:
ar5 = np.array([[1,2,3],[4,5,6],[7,8,9]])
ar5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
ar5.shape

(3, 3)

In [22]:
ar5.size

9

In [23]:
ar5.dtype

dtype('int64')

In [24]:
ar5.min()

np.int64(1)

In [25]:
ar5.max()

np.int64(9)

In [26]:
ar5.sum()

np.int64(45)

In [27]:
np.sum(ar5,axis =0 )
# axis 0 gives sum of cols, axis= 1 gives sum of rows

array([12, 15, 18])

In [28]:
ar5.mean()

np.float64(5.0)

In [29]:
ar5.std()

np.float64(2.581988897471611)

In [30]:
ar5.argmax()
# gives the index of max element

np.int64(8)

In [31]:
ar5.argmin()
# gives the index of min element

np.int64(0)

In [33]:
ar6 = np.arange(1,13)
ar6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [34]:
ar6.reshape(4,3)
# since ar6 have 12 element and 4*3 =12 so it can be reshaped

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [35]:
# Numpy indexing and slicing of vectors

ar7= np.arange(11,21)
ar7
# index start from zero 

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [36]:
ar7[1]

np.int64(12)

In [37]:
ar7[1:6:2]
# in slicing start: end :steps and traverse till end-1

array([12, 14, 16])

In [38]:
ar8 = np.arange(1,31).reshape(6,5)
ar8

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [39]:
ar8[0,1]

np.int64(2)

In [41]:
ar8[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [52]:
# boolean indexing
ar9= np.arange(11,21)
ar9

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [53]:
bool_index = ar9 % 2== 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [54]:
ar9= ar9[bool_index]
ar9

array([12, 14, 16, 18, 20])

In [5]:
# array operations 1. arithmatic operation
arr1=np.array ([1,2,3,4])
arr2= np.array([3,4,5,6]) 
arr1+ arr2
# lenth should be same of array


array([ 4,  6,  8, 10])

In [6]:
arr2 - arr1

array([2, 2, 2, 2])

In [7]:
arr2 / arr1

array([3.        , 2.        , 1.66666667, 1.5       ])

In [8]:
# arr2 * arr1 and arr1** arr2  
arr2 // arr1 
# float devision gives only integers

array([3, 2, 1, 1])

In [9]:
# 2. broadcasting
# one operation is applied on all eleement
l= [1,3,4,7]
a1 = np.array(l)
a1

array([1, 3, 4, 7])

In [10]:
a1 +10

array([11, 13, 14, 17])

In [11]:
a2= np.arange(1,31).reshape(5,6)
a2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [12]:
a2 * 2

array([[ 2,  4,  6,  8, 10, 12],
       [14, 16, 18, 20, 22, 24],
       [26, 28, 30, 32, 34, 36],
       [38, 40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58, 60]])

In [3]:
# deep and shallow copy
a =np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [15]:
slice= a[:5]
slice

array([1, 2, 3, 4, 5])

In [16]:
add= slice+ 10
add

array([11, 12, 13, 14, 15])

In [17]:
a
# if we slice a array and make changes in it,then it does not reflect in main array is called shallow copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [18]:
b= a 
# now b and a loacation are same so if we make changes in b it will reflect in a called deep copy
b[0]= 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [19]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [22]:
# to avoid deep copy we can use .copy function
f= np.arange(1,11)
b = f.copy()
b[0]= 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
# matrix operation
A= np.array([[1,2],[3,4]])
B= np.array([[5,6],[7,8]])
A

array([[1, 2],
       [3, 4]])

In [27]:
B

array([[5, 6],
       [7, 8]])

In [28]:
A* B
# normal multiplication

array([[ 5, 12],
       [21, 32]])

In [30]:
A @ B
# it give matrix multiplication

array([[19, 22],
       [43, 50]])

In [31]:
# for dot product
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [32]:
# for transpose
A.T

array([[1, 3],
       [2, 4]])

In [33]:
# Advanced array manipulation   1. stacking of array
# we can not stack two matrix . we jave to stack vectors or arrays
s= np.array([1,2,3,4])
t= np.array([5,6,7,8])

In [34]:
np.vstack((s,t))
# stacked vertically

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [36]:
np.hstack((s,t))
# stacked horizontally

array([1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
np.column_stack((s,t))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [38]:
# splitig array
c= np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [39]:
np.hsplit(c,2)
# it splits the array horizontally in 2 parts. since it has 4 columns we can not split it in 3 parts.

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [40]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [41]:
np.vsplit(c,4)
# it splited into 2D matrix

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]